apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-common-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Enabled: "true"
  RabbitMq__Host: rabbitmq
  RabbitMq__VirtualHost: /
  RabbitMq__Username: guest
  Jwt__Issuer: fcg-users-api
  Jwt__Audience: fcg-services
  Redis__ConnectionString: "redis:6379"
  Redis__InstanceName: "fcg-catalog:"
  Mongo__Enabled: "true"
  Mongo__ConnectionString: "mongodb://mongodb:27017"
  Mongo__DatabaseName: fcg_catalog
  Mongo__ReviewsCollectionName: game_reviews
