apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-common-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Enabled: "true"
  RabbitMq__Host: rabbitmq
  RabbitMq__VirtualHost: /
  RabbitMq__Username: guest
  Jwt__Issuer: fcg-users-api
  Jwt__Audience: fcg-services
