apiVersion: v1
kind: Secret
metadata:
  name: fcg-rabbitmq-secret
  namespace: fcg
type: Opaque
stringData:
  RabbitMq__Password: guest
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: fcg-jwt-secret
  namespace: fcg
type: Opaque
stringData:
  Jwt__SecretKey: development-secret-key-change-before-production
---
apiVersion: v1
kind: Secret
metadata:
  name: fcg-seed-admin-secret
  namespace: fcg
type: Opaque
stringData:
  SeedData__Admin__Password: Admin@123
